%%  I.Recent economic developments, 2019-22 (Rwametric database, reportHistory, source files)
%I.D. Nominal/real interest & exchange rates, monetary aggregates-calibration
%Nominal and real interest rates (relative to trends) and monetary aggregates
%This codes can be used to replicate other necessary variable charts (final
%demand and inflation)
clear, clc, close all
load("results/data.mat");
load("results/Filter.mat");

%plot and highlight ranges
plotRange = qq(2015,1) : qq(2022,2);
HighRange = qq(2015,1) : qq(2019,2); %Highight the past (2019 backward)
%% 1. Nominal and real int. rates
figure ();
plot(plotRange, dbObs.obs_i,...
'linewidth', 2,...
'color', 'k');
hold on
plot(plotRange, dbFilt.mean.i_tnd,...
'linewidth', 2);
%'color', '');
hold on
plot(plotRange, dbObs.obs_i_repo,...
'linewidth', 2);
plot(plotRange, dbObs.obs_i_pol,...
'linewidth', 2);
legend ('Policy_(IB)_rate', 'IB_trend','Repo_rate', 'CBR',...
    'interpreter', 'none','Fontsize',12,...
'location', 'southoutside',...
  'orientation', 'horizontal');
zeroline
grid on
highlight(HighRange); %,'EdgeColor','m','LineWidth',1.5);
title('Money market interest rates', 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/IB_hist.tif');
%% IB, RIR and cpi_core
figure ();
plot(plotRange, dbFilt.mean.i,...
'linewidth', 2,...
'color', 'k');
hold on
plot(plotRange, dbFilt.mean.r,...
'linewidth', 2);
plot(plotRange, dbFilt.mean.e_dl_cpi_core,...
'linewidth', 2);
legend ('IB_rate', 'RIR', 'Exp_cpi_core',...
    'interpreter', 'none','Fontsize',12,...
'location', 'southoutside',...
  'orientation', 'horizontal');
zeroline
grid on
highlight(HighRange); %,'EdgeColor','m','LineWidth',1.5);
title('Policy rate (IB), RIR, CPI_core{+1}', 'FontSize',12,...
    'interpreter', 'none');
%% RIR and trend
figure ();
plot(plotRange, dbFilt.mean.r,...
'linewidth', 2);
%'color', 'b');
hold on
plot(plotRange, dbFilt.mean.r_tnd,...
'linewidth', 2);
%'color', 'r');
hold on
plot(plotRange,dbFilt.mean.r4_gap,...
'linewidth', 2);
legend ('RIR_[r]_(yoy.%)','RIR_trend','RIR_[r4gap]_(+4Q)]','interpreter', 'none','Fontsize',12,...
'location', 'southoutside',...
  'orientation', 'horizontal');
zeroline
grid on
highlight(HighRange); %,'EdgeColor','m','LineWidth',1.5);
title('Real interest (policy) rates', 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/RIR_hist.emf');
%% interest (IB) rate decomposition
i_decomp = dbEqDecomp.i;
figure ();
barcon(plotRange,i_decomp.decompContribs{1}, ...
  'colormap', parula);
hold on
plot(plotRange, i_decomp.decompSeries{1}, ...
  'linewidth', 3, ...
  'color',    'w');
plot(plotRange, i_decomp.decompSeries{1}, ...
  'linewidth', 2, ...
  'color',    'k');
grid on
legend(i_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);
title(i_decomp.figureName, 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/IB_hist_decomp.emf');
%% RIR tnd decomposition
% r_tnd affects r thru i_tnd then to i
r_decomp = dbEqDecomp.r_tnd;
figure ();
barcon(plotRange,r_decomp.decompContribs{1}, ...
  'colormap', parula);
hold on
plot(plotRange, r_decomp.decompSeries{1}, ...
  'linewidth', 4, ...
  'color',    'w');
plot(plotRange, r_decomp.decompSeries{1}, ...
  'linewidth', 2, ...
  'color',    'b');
grid on
legend(r_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);
title(r_decomp.figureName, 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/RIRtnd_hist_decomp.emf');
%% nominal and real exchange rates (relative to trends)
% Exhange rate vs. target
figure ();
plot(plotRange, dbFilt.mean.dl_s,...
'linewidth', 2);
%'color', 'b');
hold on
plot(plotRange, dbFilt.mean.dl_s_tar,...
'linewidth', 2);
legend ('Nom_ER','ER_tar','interpreter', 'none','Fontsize',12,...
'location', 'southoutside',...
  'orientation', 'horizontal');
zeroline
grid on
highlight(HighRange); %,'EdgeColor','m','LineWidth',1.5);
title('Exchange rate(ER),ann. QQ % vs. target', 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/ER_hist.emf');
%% Exhange Rate (ER) decomposition
er_decomp = dbEqDecomp.l_s;
figure ();
barcon(plotRange,er_decomp.decompContribs{1}, ...
  'colormap', parula);
hold on
plot(plotRange, er_decomp.decompSeries{1}, ...
  'linewidth', 3, ...
  'color',    'w');
plot(plotRange, er_decomp.decompSeries{1}, ...
  'linewidth', 2, ...
  'color',    'b');
grid on
legend(er_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);
title(er_decomp.figureName, 'FontSize',12,...
    'interpreter', 'none');
exportgraphics(gcf, 'graphs/IB_hist_decomp.emf');
%% RER and trend
figure ();
plot(plotRange, dbFilt.mean.dl_z,...
'linewidth', 2);
%'color', 'b');
hold on
plot(plotRange, dbFilt.mean.dl_z_tnd,...
'linewidth', 2);
legend ('RER_gap','ER_trend','interpreter', 'none','Fontsize',12,...
'location', 'southoutside',...
  'orientation', 'horizontal');
zeroline
grid on
highlight(HighRange); %,'EdgeColor','m','LineWidth',1.5);
title('Real exchange rate(RER),ann. QQ % vs. trend', 'FontSize',12,...
    'interpreter', 'none');
%exportgraphics(gcf, 'graphs/RIR_hist.tif');
exportgraphics(gcf, 'graphs/ER_tnd_hist.emf');
%% RER decomposition
figure ();
decomp_RER = [dbFilt.mean.dl_s,...
    dbFilt.mean.dl_cpistar,...
   -dbFilt.mean.dl_cpi_core];
dl_z = dbFilt.mean.dl_z; %tot RER
barcon(plotRange,decomp_RER,'colormap', parula)
legend ('Nom_ER', 'CPI_star','CPI_core', 'interpreter','none',...
    'location', 'southoutside',...
  'orientation', 'horizontal');
hold on
grid on
plot(plotRange, dl_z, 'linewidth', 3, 'color', 'w');
hold on
plot(plotRange, dl_z, 'linewidth', 2, 'color', 'b');
legend ('Nom_ER', 'CPI_star','CPI_core', 'interpreter','none',...
    'location', 'southoutside',...
  'orientation', 'horizontal', ...
  'fontsize', 12);
highlight(HighRange)
title('Real exchange rate,ann.QQ % (dl_z)', 'fontsize', 12,...
    'interpreter','none');
exportgraphics(gcf, 'graphs/RER_hist_decomp.tif');

%% Final demand components
% 1.Cosumption decomposition 
cons_decomp = dbEqDecomp.l_cons_gap;
figure ();
barcon(plotRange,cons_decomp.decompContribs{1}, ...
  'colormap', parula);
hold on
plot(plotRange,cons_decomp.decompSeries{1}, ...   
  'linewidth', 3, ...
  'color',    'w');
plot(plotRange, cons_decomp.decompSeries{1}, ...
  'linewidth', 2 ...
  , ...
  'color',    'k');
grid on
legend(cons_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);%'EdgeColor','m','LineWidth',1.5);
title(cons_decomp.figureName, 'interpreter', 'none');
exportgraphics(gcf,'graphs/import_decomp.tif');

%% 2.Investiment decomposition 
inv_decomp = dbEqDecomp.l_inv_gap;
figure ();
barcon(plotRange, inv_decomp.decompContribs{1}, ... 
  'colormap', parula);
hold on
plot(plotRange, inv_decomp.decompSeries{1}, ...    
  'linewidth', 3, ...
  'color',    'w');
plot(plotRange, inv_decomp.decompSeries{1}, ...
  'linewidth', 2 ...
  , ...
  'color','k');
grid on
legend(inv_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);%'EdgeColor','m','LineWidth',1.5);
title(inv_decomp.figureName, 'interpreter', 'none');
exportgraphics(gcf,'graphs/cons_decomp.tif');
%% Inflation(core, food and energy)
core_decomp = dbEqDecomp.dl_cpi_core;
figure ();
barcon(plotRange,core_decomp.decompContribs{1}, ... 
  'colormap', parula);
hold on
plot(plotRange,core_decomp.decompSeries{1}, ...    
  'linewidth', 3, ...
  'color',    'w');
plot(plotRange,core_decomp.decompSeries{1}, ...
  'linewidth', 2 ...
  , ...
  'color','k');
grid on
legend(core_decomp.legendEntries, ...
  'location', 'southoutside', ...
  'orientation', 'horizontal');
highlight(HighRange);%'EdgeColor','m','LineWidth',1.5);
title(core_decomp.figureName, 'interpreter', 'none');
exportgraphics(gcf,'graphs/core_decomp.tif');
%end